source 'https://rubygems.org'
gem 'activerecord'
gem 'pg'
gem 'dry-container'
gem 'dry-auto_inject'
gem 'logger'
gem 'ruby-kafka'
gem 'websocket-client-simple', require: false
gem 'sinatra', require: false
gem 'sinatra-contrib', require: false
